name: Build

on:
  schedule:
    - cron: "0 9 * * *"
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - "*"
      - '!gh-pages'

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable

    name: ${{ matrix.version }} - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest

      #services:
      #      postgres:
      #        image: postgres
      #        env:
      #          POSTGRES_PASSWORD: password
      #          POSTGRES_USER: postgres
      #          POSTGRES_DB: postgres
      #        options: >-
      #          --health-cmd pg_isready
      #          --health-interval 10s
      #          --health-timeout 5s
      #          --health-retries 5
      #        ports:
      #          - 5432:5432
      #
      #      maria:
      #        image: mariadb
      #        env: 
      #          MARIADB_USER: "maria"
      #          MARIADB_PASSWORD: "password"
      #          MARIADB_ROOT_PASSWORD: "password"
      #          MARIADB_DATABASE: "maria"
      #        options: >-
      #          --health-cmd="mysqladmin ping"
      #          --health-interval=10s
      #          --health-timeout=5s
      #          --health-retries=10
      #        ports:
      #          - 3306:3306

    steps:
      - uses: actions/checkout@v2
      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            node_modules
            ./docs/openapi/node_modules
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            #      - name: load env
            #        run: |
            #          source .env_sample \
            #            && echo "POSTGRES_DATABASE_URL=$POSTGRES_DATABASE_URL" >> $GITHUB_ENV \
            #            && echo "MARIA_DATABASE_URL=$MARIA_DATABASE_URL" >> $GITHUB_ENV

            #      - uses: actions/setup-node@v2
            #        with:
            #          node-version: "16.x"

      - name: configure GPG key
        if: (github.ref == 'refs/heads/master' || github.event_name == 'push') && github.repository == 'realaravinth/dumbserve'
        run: echo -n "$RELEASE_BOT_GPG_SIGNING_KEY" | gpg --import
        env: 
          RELEASE_BOT_GPG_SIGNING_KEY: ${{ secrets.RELEASE_BOT_GPG_SIGNING_KEY }}

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}-x86_64-unknown-linux-gnu
          profile: minimal
          override: true

            #      - name: Run migrations
            #        run: make migrate
            #        env:
            #          POSTGRES_DATABASE_URL: "${{ env.POSTGRES_DATABASE_URL }}"
            #          MARIA_DATABASE_URL: "${{ env.MARIA_DATABASE_URL }}"
            #          

      - name: build
        run: make
          #        env:
          #          POSTGRES_DATABASE_URL: "${{ env.POSTGRES_DATABASE_URL }}"
          #          MARIA_DATABASE_URL: "${{ env.MARIA_DATABASE_URL }}"

            #      - name: build frontend
            #        run: make frontend
            #
            #      - name: lint frontend
            #        run: yarn lint

      - name: run tests
        run: make test
          #        env:
          #          POSTGRES_DATABASE_URL: "${{ env.POSTGRES_DATABASE_URL }}"
          #          MARIA_DATABASE_URL: "${{ env.MARIA_DATABASE_URL }}"

      - name: Login to DockerHub
        if: (github.ref == 'refs/heads/master' || github.event_name == 'push') && github.repository == 'realaravinth/dumbserve'
        uses: docker/login-action@v1
        with:
          username: realaravinth
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: publish docker images
        if: (github.ref == 'refs/heads/master' || github.event_name == 'push') && github.repository == 'realaravinth/dumbserve'
        run: make docker-publish

      - name: publish bins
        if: (github.ref == 'refs/heads/master' || github.event_name == 'push') && github.repository == 'realaravinth/dumbserve'
        run: ./scripts/publish.sh master latest

      - name: generate documentation
        if: matrix.version == 'stable' && (github.repository == 'realaravinth/dumbserve')
        run: make doc
        env:
          #          POSTGRES_DATABASE_URL: "${{ env.POSTGRES_DATABASE_URL }}"
          #          MARIA_DATABASE_URL: "${{ env.MARIA_DATABASE_URL }}"
          GIT_HASH: 8e77345f1597e40c2e266cb4e6dee74888918a61 # dummy value
          COMPILED_DATE: "2021-07-21"

      - name: Deploy to GitHub Pages
        if: matrix.version == 'stable' && (github.ref == 'refs/heads/master' && github.repository == 'realaravinth/dumbserve')
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/doc
